libktx/ktx

collections/src/main/kotlin/ktx/collections/arrays.kt
collections/src/test/kotlin/ktx/collections/arraysTest.kt

Kotlin std array and list extensions have this property and it's super useful in for loops

Added lastIndex utility property

---

CHANGELOG.md
app/src/main/kotlin/ktx/app/application.kt

As issue #54 states, it's a useful information for the user. e.g. interpolation/extrapolation between frames.

Make timeSinceLastRender protected

---

CHANGELOG.md
build.gradle
collections/README.md
collections/src/main/kotlin/ktx/collections/arrays.kt
collections/src/main/kotlin/ktx/collections/lists.kt
collections/src/main/kotlin/ktx/collections/maps.kt
collections/src/main/kotlin/ktx/collections/sets.kt
collections/src/test/kotlin/ktx/collections/arraysTest.kt
collections/src/test/kotlin/ktx/collections/listsTest.kt
collections/src/test/kotlin/ktx/collections/mapsTest.kt
collections/src/test/kotlin/ktx/collections/setsTest.kt

#58 
Add
* `map`
* `filter`
* `flatten`
* `flatMap`
methods to 
* `GdxArray`
* `GdxList`
* `GdxMap`
* `GdxSet`
By the way I feel using `assertEqual` to check elements in a collection is pretty tedious and there must be a way to wrap it as an one-liner like `assertThat(result, SomeMagicalMatcher(listOf(1,2,3)))` or something. But I don't want to do refactor here.

Collection operations for gdx collections

---

CHANGELOG.md
inject/src/main/kotlin/ktx/inject/inject.kt
inject/src/test/kotlin/ktx/inject/injectTest.kt

I recommend to swap the bindSingleton parameters and put the "vararg to: Class<out Type>" as first paramter, like it is already done for the bind() functions.
Also added higher-order function parameters which allow now to use lambda expression for bindSingleton() as well.
F.e.
```
bindSingleton {
if (something) AndroidImplementation() else DesktopImplementation()
}
bindSingleton (Implementation::class.java) {
if (something) AndroidImplementation() else DesktopImplementation()
}
```
Hope I did everything right this time :)

Add higher-order function parameters to bindSingleton() functions.

---

ashley/src/main/kotlin/ktx/ashley/engines.kt
ashley/src/test/kotlin/ktx/ashley/EnginesSpec.kt

Note that PooledEngine already throws a RuntimeException with an appropriate message "Class cannot be created (missing no-arg constructor)", instead of returning null.
`Engine.create` still catches the Exception and throws a`CreateComponentException` for consistency between the two Engine types.

Throw an appropriate exception if createComponent fails

---

style/src/main/kotlin/ktx/style/style.kt
style/src/test/kotlin/ktx/style/styleTest.kt

Example:
enum class Drawables {
buttonUp,
buttonDown,
buttonChecked;
}
skin(myAtlas) {
button {
up = it[buttonUp]
down = it[buttonDown]
}
}

Type-safe enum names without invoke() method and brackets

---

CHANGELOG.md
style/src/main/kotlin/ktx/style/style.kt
style/src/test/kotlin/ktx/style/styleTest.kt

Closes #188 
`Skin.get` was an infix method. I'm not sure how useful that is... why would someone choose the infix syntax over the bracket syntax? It prevented adding default parameter values so I removed it and update the tests and changelog.

Added default parameter value for Skin.get

---

json/README.md
json/build.gradle
json/gradle.properties
json/src/main/kotlin/ktx/json/json.kt
json/src/test/kotlin/ktx/json/jsonTest.kt
settings.gradle

Improves syntax with type inference and improves type safety of LibGDX Json reader and writer. The module doesn't add anything new, just reified extension function.
I didn't do the readme yet because I realized this module doesn't add any functionality apart from syntax, unlike other modules. For the same reason, only minimal tests were made.

Added json extensions module

---

CHANGELOG.md
actors/README.md
actors/src/main/kotlin/ktx/actors/actions.kt
actors/src/test/kotlin/ktx/actors/actionsTest.kt

An implementation of what we discussed in issue #206.
(Edited post discussion and review)
- All unwrapping removed because it is bug-prone.
- `then` is now mutating if the first action is a SequenceAction. The second action is simply added to it.
- `+` is still non-mutating.
- `parallelTo` deprecated for new `along`
- `along` is mutating if the first action is a ParallelAction. The second action is simply added to it.
- `/` added to make ParallelActions without mutating.

SequenceAction and ParallelAction functions refactoring

---

CHANGELOG.md
style/README.md
style/src/main/kotlin/ktx/style/style.kt
style/src/test/kotlin/ktx/style/styleTest.kt

Added more extension methods to Skin with reified parameters and/or default style name as default parameter value. Here's the changes in syntax with resources named "default":
```kotlin
// Optional
val res: Resource? = skin.optional("default", Resource::class.java)
val res: Resource? = skin.optional()
// Add
skin.add("default", resource)
skin.add(resource)
skin += resource
// Remove
skin.remove("default", Resource::class.java)
skin.remove<Resource>()
// Has
val found = skin.has("default", Resource::class.java)
val found = skin.has<Resource>()
// Get all
val map: ObjectMap<String, Resource>? = skin.getAll(Resource::class.java)
val map: ObjectMap<String, Resource>? = skin.getAll()
```
So now Skin can be fully used without having `Resource::class.java` type arguments and `"default"` name …

Added more reified skin extension methods with default style name parameter

---

assets/README.md
assets/src/main/kotlin/ktx/assets/assets.kt
assets/src/test/kotlin/ktx/assets/assetsTest.kt

This is for #222 .
A few notes:
- `members` is protected so it can be accessed by the protected `asset()` and `delayedAsset()` inline functions. There's also an internal `@PublishedApi` for it so it can be used for the `unloadAllSafely()` inline function. But I thought in some cases someone might want to customize the `asset()`/`delayedAsset()` functions and therefore need a way to directly add to the set.
- I added `toString()` for the two types of assets so reacting to caught exceptions in `unloadAllSafely()`  gives you something that is useful to log. Otherwise, you have very little clue as to which asset threw the exception.
- I made MockAsset throw an exception if disposed twice, which is something some Gdx classes do, so I thought it would help effectively test safe unloading.

AssetGroup

---

collections/README.md
collections/src/main/kotlin/ktx/collections/arrays.kt
collections/src/test/kotlin/ktx/collections/arraysTest.kt

These two functions could not be used if you want to free the removed items to a pool. The alternative would be to return the removed items, but that would create allocation/GC churn for something that is not always needed. And by far the most likely thing you would ever do with a removed item, if anything,  is return it to a pool.
I elected not to add this to `filter` as you would likely not use `filter` with pooled items. Pooled items are used in situations where the array is probably large and allocation/GC churn is trying to be avoided, so you would likely also want to be doing an in-place filter with `retainAll`.

Optional pool freeing when using removeAll or retainAll

---

collections/src/main/kotlin/ktx/collections/arrays.kt
collections/src/test/kotlin/ktx/collections/arraysTest.kt

A couple of changes I hadn't pushed yet when #232 was merged.
`removeAll` and `retainAll` should return Boolean like the stlib functions do.
And I thought `transfer` could be less strict about the target array type.

removeAll/retainAll return Boolean; transfer less strict

---

CHANGELOG.md
actors/README.md
actors/src/main/kotlin/ktx/actors/events.kt
actors/src/test/kotlin/ktx/actors/eventsTest.kt

Adds touch event extensions for actors. I saw that the `InputEvent` actually has the information if a touchdown or touchup event is happening (InputEvent has a `type` which indicates that).
I did not use that at the moment but maybe it would be a better approach then the current one so that the user only specifies one lambda and in there he can add an if to either execute the down or up code.
Also, `touchDown` requires a boolean return type because only if `true` is returned then the `touchUp` for that actor will be called.
I don't know when you would return false but because of that the down lambda currently expects a boolean return type.
What do you think? Should we keep the extensions as they are right now (maximum flexibility) or should we simplify it?

(#238) adds touch event extensions for actors

---

async/README.md
async/src/main/kotlin/ktx/async/async.kt
async/src/test/kotlin/ktx/async/asyncTest.kt

Felt like this was missing. Not sure if it should be called `KtxScope()` for naming consistency, or if that makes it too vague.

RenderScope() factory function

---

CHANGELOG.md
preferences/README.md
preferences/build.gradle
preferences/gradle.properties
preferences/src/main/kotlin/ktx/preferences/preferences.kt
preferences/src/test/kotlin/ktx/preferences/preferencesTest.kt
settings.gradle

Hi,
was working on preferences in my game and saw there is no nice kotlin extensions. I tried to come up with something but I was not sure how to solve `get` calls to avoid `getInt`, `getString`, etc..
Any ideas?
I will work on the documentation next week, if someone thinks this might be a useful addition. If not, feel free to delete this PR ;)

Preferences API extensions

---

.travis.yml
assets-async/src/test/kotlin/ktx/assets/async/storageLoadingTest.kt
assets-async/src/test/kotlin/ktx/assets/async/storageTest.kt

See #182.
* Eased off tests checking progress - with its eventual consistency, its state is not guaranteed to match `AssetStorage`, especially with multiple threads.
* Using mocked `Audio` implementation, as OpenAL is not available in Travis and floods the console with logs.

Updated AssetStorage tests on Travis

---

assets/README.md
assets/src/main/kotlin/ktx/assets/disposables.kt
assets/src/test/kotlin/ktx/assets/DisposablesTest.kt

This is a tool I've been using lately to make it easy to keep track of all the Disposable instances stored in fields of a class so I won't miss disposing of them.
The way I use it is by instantiating a concrete implementation as a delegate. This exposes an `.alsoRegister()` extension function for Disposables so they can be registered right where you instantiate them. Then they are easy to dispose all together. Example:
```kotlin
class MyLoadScreen: Screen, DisposableRegistry by DisposableContainer() {
private val batch = SpriteBatch().alsoRegister()
private val logoTexture = Texture("myLogo.png", true).apply {
setFilter(TextureFilter.Linear, TextureFilter.MipMapLinearLinear)
alsoRegister()
}
//...
override fun dispose() {
disposeRegisteredSafely()
}
}
```
The reason for the interface is …

DisposableRegistry

---

CHANGELOG.md
tiled/README.md
tiled/src/main/kotlin/ktx/tiled/mapLayers.kt
tiled/src/main/kotlin/ktx/tiled/mapObjects.kt
tiled/src/main/kotlin/ktx/tiled/tiledMaps.kt
tiled/src/test/kotlin/ktx/tiled/MapLayerTest.kt
tiled/src/test/kotlin/ktx/tiled/MapObjectTest.kt
tiled/src/test/kotlin/ktx/tiled/TiledMapTest.kt

Some small extensions that I introduced in my own project and that might be useful for others:
- `isEmpty` and `isNotEmpty` for `MapLayers` and `MapObjects` class
- `forEachLayer` for `TiledMap` class. The purpose of this function in my case was that I needed a way to iterate over a specific type of layers. LibGDX has a `getByType` function as part of `MapLayers` class. However, this function internally always creates an array and returns it as a result or you need to pass in an array that gets filled with those layers. 
I did not like that and that is the reason for the `forEachLayer` extension. It does basically the same but without the need of an additional array object.
Let me know if this is useful or not and in case it is useful if it requires changes or not ;)

isEmpty, isNotEmpty and forEachLayer for ktx-tiled

---

CHANGELOG.md
gradle/wrapper/gradle-wrapper.properties

This PR updates Gradle from ```6.8.3``` to ```7.0.2```.
Nothing else is changed or modified.

Update Gradle to 7.0.2

---

.github/CONTRIBUTING.md
CHANGELOG.md
README.md
ai/README.md
ai/build.gradle.kts
ai/gradle.properties
ai/src/main/kotlin/ktx/ai/behaviorTree.kt
ai/src/test/kotlin/ktx/ai/BehaviorTreeTest.kt
ai/src/test/kotlin/ktx/ai/BranchTasksTest.kt
ai/src/test/kotlin/ktx/ai/Cat.kt
ai/src/test/kotlin/ktx/ai/DecoratorsTest.kt
ai/src/test/kotlin/ktx/ai/EatTask.kt
ai/src/test/kotlin/ktx/ai/LeafTasksTest.kt
ai/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
buildSrc/src/main/kotlin/ktx/Versions.kt
settings.gradle.kts

This adds a GdxAI module with utilities for BehaviorTree and its various tasks (see discussion #436).

GdxAI module

---

scene2d/src/main/kotlin/ktx/scene2d/factory.kt
scene2d/src/test/kotlin/ktx/scene2d/factoryTest.kt

PR for #485.
I did not adjust the factory methods for Texture, TextureRegion and NinePatch because I think they will throw an exception, but more importantly, I think in those cases it does not make sense. Drawable and drawable name do make sense because in a Skin, from what I know, you can reference Drawables and in the case of an image they are optional.

(#485) make drawable and drawableName optional for scene2d image factory

---

.github/workflows/publish-project-samples.yml

`gdx-liftoff` now seems to require JDK 17, which prevents the automated sample publishing pipeline from working correctly.
See #489.

Update sample workflow to Java 17
