libktx/ktx

- .github/CONTRIBUTING.md
- README.md
> Fixed repository links. #50

- README.md
> Added ktx-ashley description. #106

- ashley/README.md
- ashley/src/main/kotlin/ktx/ashley/engines.kt
- ashley/src/test/kotlin/ktx/ashley/EnginesSpec.kt
https://github.com/libktx/ktx/issues/94
> Use default functional parameters for ktx-ashley

- README.md
> Added graphics module to README.

- CHANGELOG.md
- graphics/README.md
- graphics/src/main/kotlin/ktx/graphics/shapeRenderer.kt
- graphics/src/test/kotlin/ktx/graphics/shapeRendererTest.kt
Addresses #162 
The test passes, but since the test runs on a mock, I must confess I haven't yet run this live. (I haven't looked up yet how to link my project against a local fork of libktx instead of using the one from the repo.)
> ShapeRenderer.use()

- async/src/main/kotlin/ktx/async/assets/wrapper.kt
- async/src/main/kotlin/ktx/async/async.kt
- async/src/main/kotlin/ktx/async/http.kt
- async/src/test/kotlin/ktx/async/asyncTest.kt
- async/src/test/kotlin/ktx/async/httpTest.kt
- async/src/test/kotlin/ktx/async/utils.kt
- gradle.properties
https://github.com/libktx/ktx/issues/154
> Update to kotlin coroutines 1.0.1

- ashley/build.gradle
https://github.com/libktx/ktx/issues/173
> Remove deprecated Junit Gradle Plugin

- README.md
Hey guys, I just did a minor typo fix here. 
Currently looking into libGDX + kotlin (trying to learn both at the same time 😄). Found your project and was impressed. I guess I need to learn the libGDX api first though 😃
> Update README.md (typo fix)

- CHANGELOG.md
- app/src/main/kotlin/ktx/app/graphics.kt
- app/src/test/kotlin/ktx/app/gameTest.kt
- app/src/test/kotlin/ktx/app/graphicsTest.kt
this was branched off of develop instead of master.
> adding depth buffer clear to clearScreen for screens with 3d graphics

- CHANGELOG.md
- graphics/README.md
- graphics/src/main/kotlin/ktx/graphics/graphics.kt
- graphics/src/test/kotlin/ktx/graphics/graphicsTest.kt
An implementation of the discussion from #210.
> Add matrix and camera parameters for batch.use

- graphics/src/main/kotlin/ktx/graphics/graphics.kt
- graphics/src/test/kotlin/ktx/graphics/graphicsTest.kt
> Added Batch.begin extension function. #214

- CHANGELOG.md
- collections/README.md
- collections/src/main/kotlin/ktx/collections/arrays.kt
- collections/src/main/kotlin/ktx/collections/lists.kt
- collections/src/test/kotlin/ktx/collections/arraysTest.kt
> removeAll and retainAll for GdxArray

- CHANGELOG.md
- math/README.md
- math/src/main/kotlin/ktx/math/ranges.kt
- math/src/test/kotlin/ktx/math/rangesTest.kt
I find myself using these frequently when I use ranges for defining characteristics of my game objects. I also ran the formatter on rangesTest.kt.
> Range interpolation functions

- CHANGELOG.md
- graphics/README.md
- graphics/src/main/kotlin/ktx/graphics/color.kt
- graphics/src/main/kotlin/ktx/graphics/graphics.kt
- graphics/src/test/kotlin/ktx/graphics/ColorTest.kt
- graphics/src/test/kotlin/ktx/graphics/GraphicsTest.kt
Its seems like there are enough changes associated with Color class to extract into a separate file.
> Added support for Color destructuring syntax #284

- assets/src/test/kotlin/ktx/assets/DisposablesTest.kt
Oops. This line was not testing for identity.
> Fix DisposableContainer identity test

- CHANGELOG.md
- scene2d/README.md
- scene2d/src/main/kotlin/ktx/scene2d/factory.kt
- scene2d/src/test/kotlin/ktx/scene2d/factoryTest.kt
I just added builders for NinePatch, TextureRegion, Texture, drawable and related tests. Fixes #299
> Image builders

- CHANGELOG.md
- collections/src/main/kotlin/ktx/collections/maps.kt
- collections/src/test/kotlin/ktx/collections/MapsTest.kt
> Added square bracket assignment support for ArrayMap. #176

- CHANGELOG.md
- README.md
- async/README.md
- buildSrc/src/main/kotlin/ktx/Versions.kt
- gradle.properties
> Kotlin updated to 1.5.31, Kotlinx Coroutines updated to 1.5.2. #375

- gradle.properties
> Dokka 1.5.30 update

- CHANGELOG.md
- actors/README.md
- actors/src/main/kotlin/ktx/actors/events.kt
- actors/src/test/kotlin/ktx/actors/EventsTest.kt
- Added support for onItemClick listeners for Trees
> Tree.onItemClick support, #398

- ashley/src/main/kotlin/ktx/ashley/properties.kt
> Added delegated properties for the Entity class

- ashley/src/main/kotlin/ktx/ashley/properties.kt
- ashley/src/test/kotlin/ktx/ashley/ComponentTagSpec.kt
> Adding TagDelegate and tagFor

- CHANGELOG.md
- README.md
- artemis/README.md
- artemis/build.gradle.kts
- artemis/gradle.properties
- artemis/src/main/kotlin/ktx/artemis/archetype.kt
- artemis/src/main/kotlin/ktx/artemis/arrays.kt
- artemis/src/main/kotlin/ktx/artemis/aspect.kt
- artemis/src/main/kotlin/ktx/artemis/entity.kt
- artemis/src/main/kotlin/ktx/artemis/mapper.kt
- artemis/src/main/kotlin/ktx/artemis/transmuter.kt
- artemis/src/main/kotlin/ktx/artemis/world.kt
- artemis/src/test/kotlin/ktx/artemis/ArchetypeSpec.kt
- artemis/src/test/kotlin/ktx/artemis/AspectSpec.kt
- artemis/src/test/kotlin/ktx/artemis/Dead.kt
- artemis/src/test/kotlin/ktx/artemis/EntitySpec.kt
- artemis/src/test/kotlin/ktx/artemis/MapperSpec.kt
- artemis/src/test/kotlin/ktx/artemis/Position.kt
- artemis/src/test/kotlin/ktx/artemis/Remove.kt
- artemis/src/test/kotlin/ktx/artemis/RigidBody.kt
- artemis/src/test/kotlin/ktx/artemis/TestSystem.kt
- artemis/src/test/kotlin/ktx/artemis/Texture.kt
- artemis/src/test/kotlin/ktx/artemis/Transform.kt
- artemis/src/test/kotlin/ktx/artemis/TransmuterSpec.kt
- artemis/src/test/kotlin/ktx/artemis/WorldSpec.kt
- buildSrc/src/main/kotlin/ktx/Versions.kt
- settings.gradle.kts
> Artemis-ODB module
